### ISSUE TITLE
GPL Violation

### ISSUE THREAD

**Issue by SciresM** [thomleg50/Fusee-STARTER#2]
As you acknowledge in the readme, this uses code taken from Atmosphere.

Atmosphere is licensed GPLv2 -- thus, your program must also be licensed GPLv2, the MIT license is not valid.

Please relicense :)

**Comment by thomleg50** [comment]
Fixed https://github.com/thomleg50/Fusee-STARTER/commit/5734343ecf5866be0d901680aed8c6cb22fa06e6

Sorry for inconvenience !
Thanks for save the scene ;)
